In 5
interenship/inctagram pull request #13
Opened 2024-09-04 07:01 UTC by yahve0110

2024-09-04 15:41 UTC, interenship commented
IN-5: feat: add documentation to select

2024-09-05 13:47 UTC, yingwai requested changes

2024-09-05 13:47 UTC, yingwai commented on src/shared/ui/Select/Select.stories.tsx
> +    ),
А это точно делается в children, а не в render?

2024-09-05 13:47 UTC, yingwai commented on src/shared/ui/Select/SelectPrimitive.ts
SelectPrimitive.ts -> selectPrimitive.ts

2024-09-05 13:49 UTC, yingwai commented on src/shared/ui/Select/Select.stories.tsx
> +    ),
Посмотри render если не видел, попробуй, если понравится я думаю лучше на него, если нет оставляй.
Измени название файлика и зальём.

2024-09-05 14:15 UTC, yingwai approved these changes

2024-09-05 14:16 UTC, merged