fix: add radiogroup with shadcn
interenship/inctagram pull request #22
Opened 2024-09-08 23:39 UTC by Yurik-00007

2024-09-09 09:20 UTC, yingwai commented
Почему fix? уже кто-то проверял? 
Чёто вообще не по теме, и названия ветки нет.
🙁

2024-09-09 09:41 UTC, yingwai commented
Вот даже к примеру, почему я обращаю на это внимание. У нас сейчас 4 ветки: main, dev и ещё 2, одна из которых точно идёт на удаление, потому что её уже залили в дев, и какая-то ветка IN-4, которую просто не удалили, или это pr? 👀
![image](https://github.com/user-attachments/assets/b86b0da9-b3df-437d-a926-b87fc82a2117)

2024-09-09 11:20 UTC, yingwai requested changes

2024-09-12 21:40 UTC, Yurik-00007 commented on src/shared/ui/RadioGroup/RadioGroup.tsx
> +import * as RadioGroupPrimitive from "@radix-ui/react-radio-group";
Я все исправил

2024-09-12 21:40 UTC, Yurik-00007 commented on src/shared/ui/RadioGroup/RadioGroup.tsx
> +RadioGroupItem.displayName = RadioGroupPrimitive.Item.displayName;
Я все исправил

2024-09-12 21:40 UTC, Yurik-00007 commented on src/shared/ui/RadioGroup/RadioGroup.stories.tsx
> +import {RadioGroup, RadioGroupItem} from "./RadioGroup";
Я все исправил

2024-09-12 21:40 UTC, Yurik-00007 commented on src/shared/ui/RadioGroup/index.ts
> +export { RadioGroup } from "./RadioGroup";
Я все исправил

2024-09-12 21:40 UTC, Yurik-00007 commented on src/shared/ui/RadioGroup/RadioGroup.tsx
> +import * as RadioGroupPrimitive from "@radix-ui/react-radio-group";
Я все исправил

2024-09-12 21:42 UTC, Yurik-00007 commented
Я все изменил , спасибо большое Жене. Все кроме названия fix на feat это я не знаю как сделать

2024-09-13 06:57 UTC, closed without merging