In 8 textarea
interenship/inctagram pull request #25
Opened 2024-09-10 17:09 UTC by yahve0110

Добавил Textarea

2024-09-12 07:37 UTC, yingwai commented
😤
> ![image](https://github.com/user-attachments/assets/fa8d69b8-c8ac-4433-9074-2368061488fe)

2024-09-12 08:07 UTC, yingwai requested changes

2024-09-12 08:07 UTC, yingwai commented on src/shared/ui/TextArea/TextArea.stories.tsx
> +};
Добавь в Meta agrs disabled: false, чтобы появился контролер управления в сторибуке.

2024-09-12 08:07 UTC, yingwai commented on src/shared/ui/TextArea/TextArea.stories.tsx
> +};
placeholder: "чё-нибудь" желательно тоже, чтобы внутри сторибука можно было проверить, а не просто непонятная кнопка Set object.

2024-09-12 08:21 UTC, EvgenyStrunevsky commented on src/shared/ui/TextArea/TextArea.tsx
> +        "focus:border-danger-500": error,
Зачем разделил эти стили?

2024-09-12 08:21 UTC, EvgenyStrunevsky commented on src/shared/ui/TextArea/TextArea.tsx
> +        "border-dark-100": !error,
О чем говорит эта проверка? Может вынести этот стиль ко всем?

2024-09-12 08:21 UTC, EvgenyStrunevsky commented on src/shared/ui/TextArea/TextArea.tsx
> +          <span className="text-danger-500 pl-[1px] text-xs">{error}</span>
Оберни ошибку в типографику

2024-09-12 08:21 UTC, EvgenyStrunevsky commented on src/shared/ui/TextArea/TextArea.tsx
> +        {label && <label className={labelClasses}>{label}</label>}
текст для лейбла оберни в типографику

2024-09-12 08:21 UTC, EvgenyStrunevsky commented on src/shared/ui/TextArea/TextArea.tsx
> +          {...props}
Свяжи textarea с label через id и htmlfor.

2024-09-12 08:36 UTC, EvgenyStrunevsky reviewed
Илья, добавь файл index.ts

2024-09-12 09:42 UTC, yahve0110 commented
Прошелся по комментария, вроде все поправил,спасибо за проверку,надо быть повнимательнее

2024-09-16 13:20 UTC, yingwai requested changes

2024-09-16 13:20 UTC, yingwai commented on src/shared/ui/TextArea/TextArea.stories.tsx
> +    labelText: "Text-area",
labelText повторяется 4 раза, его можно тоже в Meta args перенести.

2024-09-17 06:16 UTC, yingwai approved these changes

2024-09-17 06:16 UTC, merged