IN-3-Checkbox
interenship/inctagram pull request #26
Opened 2024-09-11 13:30 UTC by EvgenyStrunevsky

2024-09-12 08:13 UTC, yingwai commented
😤
![image](https://github.com/user-attachments/assets/63b4db27-d8c7-4ac4-aed6-5085bdbbdce4)

2024-09-12 08:42 UTC, yingwai requested changes

2024-09-12 08:42 UTC, yingwai commented on src/shared/ui/Typography/Typography.stories.tsx
Агааа, в шрифты полез🤣

2024-09-12 08:42 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.tsx
> +          </svg>
Это свг только пока нет компоненты?

2024-09-12 08:42 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +  },
У тебя defaultChecked не работает. И в других стори тоже.
Ну или в принципе не понятно как оно, в некоторых стори checked, в некоторых deffault, наверное было бы лучше в одном стиле.

2024-09-12 08:42 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +  },
У тебя в принципе args много повторяются, как минимум labelText и id, перенеси в Meta и выставь всё как должно быть по дефолту. А в сам стори добавляй только параметр который должен отличаться. 

Т.е. именно в этом стори останется только disabled и cheked.

Meta
 `
args: {
    labelText: "Check-box",
    id: "checkbox",
    disabled: false,
    checked: false,
    и т.д.
  },
`

Story
`
args: {
    disabled: true,
    checked: true,
  },
`

2024-09-12 13:19 UTC, EvgenyStrunevsky commented on src/shared/ui/Typography/Typography.stories.tsx
хахахаха есть немного)))

2024-09-12 13:20 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.tsx
> +          </svg>
да, пока хардкод

2024-09-12 13:53 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +  },
Отличное замечание! Мне дошло, что пропс defaultChecked передавать в управляемый чекбокс вообще не нужно. Начальное значение нужно передать в useState.

2024-09-12 13:54 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +  },
checked и defaultChecked это разные пропсы

2024-09-16 13:35 UTC, yingwai requested changes

2024-09-16 13:35 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +} satisfies Meta<typeof Checkbox>;
![image](https://github.com/user-attachments/assets/2b228a76-c062-4cab-9b5e-21bfe2425b82)

Вот это демка чекбокса в документации главная, как по мне, она должна настраиваться все возможно разно. Да, ты можешь зайти на какой-то определённый Story, и посмотреть. Но думаю важно чтобы в поле с документации было всевозможные поля чтобы кто угодно мог пощёлкать, и понять будет ли оно работать правильно. 

Потому нужно добавить сюда 
`
argTypes: {
    labelText: {
      control: { type: 'text' },
    },
  },
`
чтобы можно было менять название лэйбла.

2024-09-16 13:35 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +  render: () => {
`render: (args) => {` и тогда в Deffault Story появятся все те же параметры. А то у тебя в этой Story есть аргумент labalText, но если его менять ничего не происходит.
![image](https://github.com/user-attachments/assets/5c3df864-79d8-412b-8589-8899922c4fc2)

2024-09-16 13:35 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +    return <Checkbox checked={checkedValue} onCheckedChange={getCheckedValue} />;
И в чекбокс добавить `{...args}`, чтобы лейбел мог появится.

2024-09-16 13:35 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.tsx
> +          </svg>
Думаю уже можно менять.

2024-09-16 13:35 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +    checked: true,
disabled и checked думаю стоит по той же причине что и выше переместить в Meta, да они изначально и так false, но они просто не существуют в документации. О них можно узнать только если зайти в определённый Story.

2024-09-18 05:49 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.tsx
> +          </svg>
+

2024-09-18 05:50 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +} satisfies Meta<typeof Checkbox>;
+

2024-09-18 05:54 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +  render: () => {
+

2024-09-18 05:54 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +    checked: true,
+

2024-09-18 05:55 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +    return <Checkbox checked={checkedValue} onCheckedChange={getCheckedValue} />;
+

2024-09-18 06:06 UTC, yingwai approved these changes

2024-09-18 06:06 UTC, merged