In 17 Header
interenship/inctagram pull request #33
Opened 2024-09-18 05:42 UTC by yahve0110

Добавил Header, смена опций в селекте сделана пока что локально,когда добавим возможность менять язык,тогда сделаю рефактор,число нотификаций пока что оставил в переменной внутри компоненты потому что не понятно где будем делать запрос

2024-09-18 06:05 UTC, yingwai commented
![image](https://github.com/user-attachments/assets/df1df5ab-f0d8-409f-b9d5-274df3221e2c)

2024-09-18 09:14 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +      <div className="w-full h-[1px] bg-dark-300 "></div>
ну на счёт этого там по моему своя возня из-за tailwind`а. И как раз Юра рассказывал что тоже так делал. Сам пока не использовал, так что хз чё там

2024-09-18 09:26 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +export const Header = ({ isLogged }: { isLogged: boolean }) => {
+

2024-09-18 09:33 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +            <span className="text-light-100">Inctagram</span>
![image](https://github.com/user-attachments/assets/38690112-051d-46fd-95df-e1f455f133ec)
Без спана размер не применяется

2024-09-18 09:37 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +  const handleLanguageChange = (value: string) => {
+

2024-09-18 09:37 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +                <div className="h-[13px] w-[13px] bg-danger-500 rounded-[50%] flex items-center justify-center absolute top-[6px] right-[1px]">
+

2024-09-18 09:51 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +export const Header = ({ isLogged }: { isLogged: boolean }) => {
+

2024-09-18 09:52 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +  const handleLanguageChange = (value: string) => {
+

2024-09-18 09:52 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +    setLanguage(value as Language);
+

2024-09-18 09:52 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +  };
+

2024-09-18 09:52 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +      <header className="w-full h-[60px] bg-dark-700 flex flex-col justify-center">
+

2024-09-18 09:53 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +          <div className="flex  gap-9">
+

2024-09-18 09:57 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +                <SelectItem value="Russian">Russian</SelectItem>
+

2024-09-18 09:59 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +                    Log in
+

2024-09-18 09:59 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +                  <Link href={"/signUp"}>Sign up</Link>
+

2024-09-18 10:08 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +      <div className="w-full h-[1px] bg-dark-300 "></div>
Уточнил у ChatGPT - говорит что tailwind не поддерживает псевдоэлементы напрямую,их можно добавить комбинируя с обычным css но это намного сложнее чем просто див добавить

2024-09-18 10:14 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +        <div className="flex justify-between items-center px-[64px]">
+

2024-09-20 21:54 UTC, yingwai requested changes

2024-09-20 21:54 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +  };
Могу предложить вместо type и const, сделать enum. Это будет куда удобнее, т.к. enum можно использовать как тип, так и параметр. `enum Language {
    english: "English",
    russian: "Russian",
  };` и использовать его дальше, закоменчу моменты где найду возможность.

2024-09-20 21:54 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +  const [language, setLanguage] = useState<Language>("English");
useState<Language>(Language.english);

2024-09-20 21:54 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +    return flagComponents[language] || <FlagUnitedKingdom />;
Как-то очень странно выглядит...
А почему тогда не `return flagComponents[language] || flagComponents[English];`?
Считаю это тогда вообще лишней записей и константой сверху. 
Могу предложить использовать тот же enum, `Language.english ? ... : ...`
Если же флагов будет больше, enum тоже расширяется и тут же используется.

2024-09-20 21:54 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +          "w-full h-[60px] bg-dark-700 flex justify-between items-center px-[64px] ",
Пробел в конце можно убрать))

2024-09-20 21:54 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +        </Typography.LARGE>
Курсор поинтер бы на лого добавить. 
По поводу спана, я сейчас пойду смотреть что там не работает.

2024-09-20 21:54 UTC, yingwai commented on src/shared/ui/Header/Header.tsx
> +      <div className="w-full h-[1px] bg-dark-300 "></div>
А засунуть этот div внутрь header есть возможность? Если это по сути псевдоэлемент шапки, не хотелось бы чтобы он был снаружи.

2024-09-23 05:31 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +  };
да с enum хорошая идея

2024-09-23 05:31 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +  const [language, setLanguage] = useState<Language>("English");
+

2024-09-23 05:32 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +  };
+

2024-09-23 05:41 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +          "w-full h-[60px] bg-dark-700 flex justify-between items-center px-[64px] ",
+

2024-09-23 05:42 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +        </Typography.LARGE>
+

2024-09-23 08:06 UTC, yahve0110 commented on src/shared/ui/Header/Header.tsx
> +    return flagComponents[language] || <FlagUnitedKingdom />;
+

2024-09-23 12:21 UTC, merged