IN-18 feat: add card
interenship/inctagram pull request #35
Opened 2024-09-18 16:08 UTC by Yurik-00007

2024-09-20 21:22 UTC, yingwai requested changes

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
Договаривались props разбивать внутри компоненты `props, ref`

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
И тут

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +>(({ className, ...restProps }, ref) => (
И тут

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +>(({ className, ...restProps }, ref) => (
И тут

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
И тут

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
И тут

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +        "w-[378px] rounded-sm border border-dark-300  bg-dark-500 text-light-100",
Лишний пробел))

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  <h3 ref={ref} className={cn("", className)} {...restProps} />
Удали кавычки, зачем они тут если не нужны?

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  <h3 ref={ref} className={cn("", className)} {...restProps} />
h3? Это какой-то определённый шрифт? не совсем понял, но лучше тогда типографику использовать если там подходит

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.tsx
> +  <p ref={ref} className={cn("", className)} {...restProps} />
Тут тоже самое, кавычки не нужны и типографика

2024-09-20 21:22 UTC, yingwai commented on src/shared/ui/Card/Card.stories.tsx
> +        </CardTitle>
У тебя получается Typography.H1 (т.е. тег h1) внутри тега h3. Это не правильно.
Тут 2 варианта, либо прописать в компоненте нужный тег, и передавать в него children, либо от туда вообще убрать тег.

2024-09-25 22:14 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
+

2024-09-25 22:17 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
+

2024-09-25 22:18 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +>(({ className, ...restProps }, ref) => (
+

2024-09-25 22:21 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +>(({ className, ...restProps }, ref) => (
+

2024-09-25 22:21 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
+

2024-09-25 22:21 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +  ({ className, ...restProps }, ref) => (
+

2024-09-25 22:23 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +        "w-[378px] rounded-sm border border-dark-300  bg-dark-500 text-light-100",
))

2024-09-25 23:14 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +  <h3 ref={ref} className={cn("", className)} {...restProps} />
+

2024-09-25 23:15 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +  <p ref={ref} className={cn("", className)} {...restProps} />
+

2024-09-25 23:23 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.stories.tsx
> +        </CardTitle>
+

2024-09-26 07:02 UTC, yahve0110 commented on src/shared/ui/Card/Card.stories.tsx
> +        <CardTitle className={"mx-auto"}>
нужны ли здесь { } ?

2024-09-26 07:02 UTC, Sixtyfps commented on src/shared/ui/Card/Card.stories.tsx
> +          </div>
Просмотрено

2024-09-26 07:06 UTC, Sixtyfps commented on src/shared/ui/Card/Card.tsx
> +          className,
Запятая не нужна

2024-09-26 07:09 UTC, Sixtyfps requested changes

2024-09-26 07:09 UTC, Sixtyfps commented on src/shared/ui/Card/Card.tsx
> +          className,
Запятая

2024-09-26 07:09 UTC, yahve0110 requested changes
Убрать лишние скобки там где они не нужны

2024-09-26 07:09 UTC, yahve0110 commented on src/shared/ui/Card/Card.stories.tsx
> +        <CardTitle className={"mx-auto"}>
в дальнейшем тоже  лишние { } скобки в подобных местах

2024-09-26 07:23 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.stories.tsx
> +          </div>
+

2024-09-26 07:24 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +          className,
+

2024-09-26 07:24 UTC, Yurik-00007 commented on src/shared/ui/Card/Card.tsx
> +          className,
+

2024-09-26 07:27 UTC, yahve0110 approved these changes

2024-09-26 07:34 UTC, Sixtyfps approved these changes

2024-09-27 06:05 UTC, yingwai approved these changes

2024-09-27 06:05 UTC, merged