IN-22 feat: create Label
interenship/inctagram pull request #36
Opened 2024-09-18 22:03 UTC by Yurik-00007

2024-09-20 21:02 UTC, yingwai requested changes

2024-09-20 21:02 UTC, yingwai commented on src/shared/ui/Label/Label.stories.tsx
> +      description: "Ваш id.",
Storybook это документация)) Хотелось бы как-то немножко официальнее, как desc сверху.

2024-09-20 21:02 UTC, yingwai commented on src/shared/ui/Label/Label.stories.tsx
> +  render: (args) => <Label {...args}>Your email address</Label>,
Не, здесь render использовать бесполезно. В нём нет смысла, просто добавляешь args children "Your email address" и всё. Или в мета args, тогда тут вообще ничего прописывать не нужно будет

2024-09-20 21:02 UTC, yingwai commented on src/shared/ui/Label/Label.stories.tsx
> +  render: (args) => <Label {...args}>Your email address</Label>,
Тоже самое

2024-09-23 00:35 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.tsx
> +const labelVariants = cva("text-fontS leading-lineHM font-fontWR");
+

2024-09-23 00:37 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.stories.tsx
> +      description: "Ваш id.",
+

2024-09-23 00:40 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.stories.tsx
> +  render: (args) => <Label {...args}>Your email address</Label>,
+

2024-09-23 00:41 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.stories.tsx
> +  render: (args) => <Label {...args}>Your email address</Label>,
+

2024-09-23 00:41 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.stories.tsx
> +  render: (args) => <Label {...args}>Your email address</Label>,
Спасибо большое.

2024-09-23 12:30 UTC, yingwai approved these changes

2024-09-23 12:32 UTC, yingwai requested changes
Кароче убрать чилдрен, он уже встроен скажем так, и всё.

2024-09-23 19:39 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.tsx
> +    </Root>
+

2024-09-24 10:10 UTC, EvgenyStrunevsky commented on src/shared/ui/Label/Label.tsx
> +        "block text-fontS leading-lineHM font-fontWR text-light-100",
Зачем передаешь стили для шрифта?

2024-09-24 10:10 UTC, EvgenyStrunevsky commented on src/shared/ui/Label/Label.tsx
> +  const finalId = id ?? generatedId;
id генерируется на уровне компонента в котором используется label и потом в него передается. id которое ты сгенерируешь в label бесполезно, суть id для label связать его с элементов формы, а если ты его сгенерируешь внутри label как ты его свяжешь с элементом формы?

2024-09-24 16:22 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.tsx
> +  disabled?: boolean;
-

2024-09-24 17:27 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.tsx
> +  const { className, id, disabled, ...restProps } = props;
+

2024-09-24 17:38 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.tsx
> +  const finalId = id ?? generatedId;
+

2024-09-24 19:09 UTC, EvgenyStrunevsky commented on src/shared/ui/Label/Label.tsx
> +        "block text-light-100",
Юра, чему ты задаешь цвет?

2024-09-24 20:06 UTC, Yurik-00007 commented on src/shared/ui/Label/Label.tsx
> +        "block text-light-100",
Это цвет я задаю по умалчанию, в дальнейшем он будет перезатерт через props className. цвет по умолчанию у нас black @tailwind base. На самом деле я считаю это не критично, но если нужно я уберу

2024-09-25 10:16 UTC, EvgenyStrunevsky approved these changes

2024-09-25 10:16 UTC, EvgenyStrunevsky approved these changes

2024-09-25 10:18 UTC, EvgenyStrunevsky approved these changes

2024-09-25 10:19 UTC, merged