IN-6
interenship/inctagram pull request #40
Opened 2024-09-24 18:10 UTC by Sixtyfps

2024-09-24 20:44 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +  const [inputValue, setInputValue] = useState("");
Работа с value идет при вызове TextField, а не в его теле. Удаляем

2024-09-24 20:44 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +    if (!disabled) {
Проверка на disabled лишняя, если disabled мы никуда нажать не сможем

2024-09-24 20:44 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +  };
Функция очистки передается при вызове компонента TextField и если у него тип search

2024-09-24 20:44 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +  const inputType = type === "password" && showPassword ? "text" : type;
У тебя некорректно работают разные варианты TextField. Крестик есть только у типа search

2024-09-25 11:43 UTC, yingwai commented
Название pr по примеру с другими пожалуйста сделай

2024-09-27 21:12 UTC, yingwai requested changes
Название pr пожалуйста смени

2024-09-28 12:55 UTC, yingwai requested changes
И название pr по название пожалуйста поменяй.

2024-09-28 12:55 UTC, yingwai commented on src/shared/ui/TextField/TextField.tsx
> +    <label className={cn(`w-full`, className)}>
Вроде как Label уже готов, нужно подтянуть изменения и добавить его рядом с самим инпутом.

2024-09-28 12:55 UTC, yingwai commented on src/shared/ui/TextField/TextField.tsx
> +            ],
А зачем тут обёртка в массив? Это всё можно и без него.

2024-09-28 12:55 UTC, yingwai commented on src/shared/ui/TextField/TextField.tsx
> +            type === "password" && "pr-[35px]",
Я не уверен на счёт этого, хочу чтобы остальные тоже сказали, но мб вынести тип в enum? У нас это не сам инпут, а текс филд. И вот такие сравнения будет легче делать наверное с enum: не писать `type === "text"`, а просто `TypeTextField.text && "pr-[35px]"`.
Я понимаю что скорее всего это может быть и лишняя обёртка, но не уверен.

2024-09-28 12:55 UTC, yingwai commented on src/shared/ui/TextField/TextField.tsx
> +        {(type === "text" || type === "search") && inputValue && (
Вот тоже хороший пример для enum. И ещё 2 таких же сравнения есть ниже.

2024-09-28 12:55 UTC, yingwai commented on src/shared/ui/TextField/TextField.tsx
> +type TextFieldProps = ComponentProps<"input"> & {
Я бы поменял просто на Props, оно же внутри компоненты TextField, и так понятно чьи это пропсы)

2024-09-28 12:55 UTC, yingwai commented on src/shared/ui/TextField/TextField.stories.ts
> +    disabled: false,
Все эти args перенести в Meta, и если в данной Story нужен deffault args, то сюда его не добавлять, иначе написать только его. Нам дублирование Одних и тех же аргументов с одними и теме же свойствами не нужно)

2024-09-29 20:48 UTC, Yurik-00007 commented on src/shared/ui/TextField/TextField.tsx
> +                "w-full px-2.5 border rounded-sm border-dark-100 bg-transparent leading-6 text-light-900 font-normal text-base h-9 [&::-webkit-search-cancel-button]:hidden",
[&::-webkit-search-cancel-button]:hidden" этот префикс не нужен.
leading-6 и text-base дублируют друг друга, нужно убрать leading-6

2024-09-30 12:39 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +                "w-full px-2.5 border rounded-sm border-dark-100 bg-transparent leading-6 text-light-900 font-normal text-base h-9 [&::-webkit-search-cancel-button]:hidden",
в каком браузере ты тестировал? если не прописать [&::-webkit-search-cancel-button]:hidden то плюсом к нашему кастомному появляется стандартный крестик зачистки инпута
![Screenshot 2024-09-30 at 15 38 24](https://github.com/user-attachments/assets/caeecc65-59c5-46dc-b9dd-c3d020d7ebc3)

2024-09-30 12:43 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +  // Состояние показать/скрыть password
🫡

2024-09-30 21:01 UTC, yingwai commented on src/shared/ui/TextField/TextField.tsx
> +            ],
понял, ну может быть, если удобно, я бы просто запятой отделял наверное

2024-09-30 21:13 UTC, yingwai commented
Тебе бы ещё изменения подтянуть, у тебя ветка очень старая, хз может ли быть это проблемой, но я бы лучше подтянул.

2024-09-30 21:15 UTC, yingwai commented on src/shared/ui/TextField/TextField.stories.ts
> +    disabled: false,
Так ты просто удалил label и className🙂🤔

2024-10-01 14:13 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +  const [inputValue, setInputValue] = useState("");
+

2024-10-01 14:15 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +    if (!disabled) {
+

2024-10-01 14:15 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +  };
Done

2024-10-01 14:15 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +  const inputType = type === "password" && showPassword ? "text" : type;
Done

2024-10-01 14:18 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +            type === "password" && "pr-[35px]",
Создал объект с этими типами, насчет энамки спросил на поддержке и сказали, что enum лучше использовать если он еще где-то переиспользуется в проекте, либо содержит какие-то числовые значения, у нас тут типы только моего text field и без числовых значений, поэтому создал объект с этими типами

2024-10-01 14:20 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +        {(type === "text" || type === "search") && inputValue && (
Починено

2024-10-01 14:27 UTC, yahve0110 commented
В сторибуке нет варианта с ошибкой,а еще договаривались вместо label использовать компоненту Label,тебе наверное надо подтянуть изменения в дев и смерджиться чтобы она появилась

2024-10-03 12:51 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +    <label className={cn(`w-full`, className)}>
Done

2024-10-03 12:52 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.stories.ts
> +    disabled: false,
Done

2024-10-03 12:52 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +type TextFieldProps = ComponentProps<"input"> & {
тут вопросы, пока оставлю так, если что - поменяю

2024-10-07 17:46 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.stories.tsx
> +};
Done

2024-10-07 21:34 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.stories.tsx
> +  },
Перенеси в argTypes `disabled: { control: "boolean" },`

2024-10-07 21:35 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.stories.tsx
> +};
Классное решение. Сделал у себя также

2024-10-07 21:36 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.stories.tsx
> +    const generatedId = useId(); // Генерация id для label и input
id генерируется только внутри компонента и если не пришел id при вызове

2024-10-07 21:37 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.stories.tsx
> +    </>
Здесь фрагмент не нужен

2024-10-07 21:39 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.stories.tsx
> +      <Label htmlFor="textfield" className={cn("text-white")}>
id нужно взять из meta

2024-10-07 21:41 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +    const generatedId = useId();
Здесь должно быть условие: пришел id - берем его, нет - генерируем

2024-10-07 21:41 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +    const generatedId = useId();
Красиво

2024-10-07 21:43 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +      id = generatedId,
сразу сюда кинь useId()

2024-10-07 21:44 UTC, EvgenyStrunevsky commented on src/shared/ui/TextField/TextField.tsx
> +                "w-full px-2.5 border rounded-sm border-dark-100 bg-transparent leading-6 text-light-900 font-normal text-base h-9 [&::-webkit-search-cancel-button]:hidden",
Напомни об этом на созвоне

2024-10-08 05:30 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +      id = generatedId,
мне кажется с переменной generatedId более читабельно

2024-10-08 05:56 UTC, Yurik-00007 commented on src/shared/ui/TextField/TextField.stories.tsx
> +};
Если props.id каким-то образом имеет значение true, то выражение станет просто true, что может вызвать проблемы в вашем коде (например, если id элемента станет true, что является некорректным идентификатором).
Альтернативное решение:
Если вам нужно, чтобы id всегда был валидным значением, попробуйте использовать функциональные подходы:
id={props.id ?? generatedId}
Оператор ?? (nullish coalescing) вернет generatedId только если props.id — это null или undefined, что может быть безопаснее в ряде случаев.

2024-10-08 09:21 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.stories.tsx
> +  },
Done

2024-10-08 09:22 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.stories.tsx
> +    const generatedId = useId(); // Генерация id для label и input
Done

2024-10-08 09:22 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.stories.tsx
> +    </>
Done

2024-10-08 09:22 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.stories.tsx
> +      <Label htmlFor="textfield" className={cn("text-white")}>
Done

2024-10-08 09:25 UTC, Sixtyfps commented on src/shared/ui/TextField/TextField.tsx
> +      id = generatedId,
Вопрос закрыт, так нельзя

2024-10-09 06:42 UTC, yahve0110 approved these changes

2024-10-09 06:44 UTC, Yurik-00007 approved these changes

2024-10-09 11:28 UTC, EvgenyStrunevsky approved these changes

2024-10-09 11:36 UTC, evgeniy-strunevskiy approved these changes

2024-10-09 12:14 UTC, yingwai approved these changes

2024-10-09 12:14 UTC, merged