In 27
interenship/inctagram pull request #45
Opened 2024-09-26 20:12 UTC by EvgenyStrunevsky

2024-09-26 22:45 UTC, Yurik-00007 commented on src/shared/ui/Checkbox/Checkbox.tsx
>    const finalId = id ?? generatedId;
А нужна ли такая заглушка в radioGroup?

2024-09-26 22:58 UTC, Yurik-00007 commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
>      },
parameters: {
    layout: "centered",
  },
  добавь чтобы было идентично как у всех

2024-09-26 22:58 UTC, Yurik-00007 commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
>      },
Мне кажеться нужно добавить еще описание id, className и onCheckedChange, это же типа документация. Посмотри у меня сделано, если не нужно скажи я тоже удалю

2024-09-26 22:58 UTC, Yurik-00007 commented on src/shared/ui/Checkbox/Checkbox.tsx
> +  const { className, id, disabled, ...restProps } = props;
disabled=false, забыл добавить

2024-09-27 04:36 UTC, yahve0110 commented
Добавь префикс в название пул реквеста

2024-09-27 07:25 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.tsx
>    const finalId = id ?? generatedId;
нужна

2024-09-27 07:25 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.tsx
> +  const { className, id, disabled, ...restProps } = props;
+

2024-09-27 07:27 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
>      },
+

2024-09-27 07:30 UTC, EvgenyStrunevsky commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
>      },
Подумал... всё-таки описание нативных пропсов, это сомнительная идея.

2024-09-28 09:32 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
>      },
Согласен, думаю нативные и так понятны

2024-09-28 10:30 UTC, yingwai requested changes

2024-09-28 10:30 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +
А зачем ты убрал то из аргументов label, почему у тебя idForCheckbox и labelText просто как константы, а не в аргументах? 
У тебя ведь даже нет никакой документации получается. Я например хочу поменять label, проверить меняется ли он, а не могу. Он просто где-то скрыт. У тебя он эти переменные просто где-то снаружи, даже не в story где он используется.

2024-09-28 10:30 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +        </Typography.MEDIUM14>
А зачем?) Почему ты убрал из аргументов cheked? Ты ведь там переключаешь или сам чекбокс переключаешь и там всё видно. Это же бессмысленно просто. Ты из документации просто всё вывел на страницу считай🤨

2024-09-28 10:30 UTC, yingwai commented on src/shared/ui/Checkbox/Checkbox.stories.tsx
> +          <Typography.REGULAR14 className={"text-light-100"}>{labelText}</Typography.REGULAR14>
Ну вот, а почему не использовать аргумент? Где я бы поменял что-то, и понял что всё ок? А так этот labelText просто не в поле видимости. Было бы меньше вопросов даже если бы он был в аргументах самой истории, а тут я вообще не понимаю ради чего)

2024-10-09 12:15 UTC, yingwai approved these changes

2024-10-10 11:17 UTC, merged